Add prefix for index
AY2223S1-CS2103T-W16-4/tp pull request #139
Opened 2022-10-10 13:53 UTC by ThomasHoooo

2022-10-10 17:15 UTC, rexong requested changes
Just 1 suggestion here. Do take a look.

2022-10-10 17:15 UTC, rexong commented on docs/UserGuide.md
> +Format: `addMeeting n/NAME d/DATE t/TIME dn/DESCRIPTION`
Just putting here as a reminder that after this iteration, we should use `i/` instead

2022-10-10 17:15 UTC, rexong commented on src/main/java/seedu/address/logic/parser/EditCommandParser.java
> +        } catch (ParseException | NoSuchElementException pe) {
Just a nitpick, since 2 exceptions are capture here, the variable name can probably consider `e` instead

2022-10-11 07:22 UTC, ThomasHoooo commented
> Just 1 suggestion here. Do take a look.

Fixed

2022-10-11 12:18 UTC, rexong approved these changes
LGTM

2022-10-11 14:16 UTC, merged