Update naming history in README
AY2223S1-CS2103T-W16-4/tp pull request #49
Opened 2022-09-29 13:26 UTC by ThomasHoooo

2022-09-29 13:56 UTC, rexong commented
Close this PR and reopen again.

2022-09-29 14:00 UTC, ThomasHoooo commented
> Close this PR and reopen again.

Don't have to, just need to re-run. Now all the checks pass.

2022-09-29 14:10 UTC, rexong requested changes

2022-09-29 14:10 UTC, rexong commented on README.md
> +* It is named `MyInsuRec` because it helps financial advisors to keep track of his client and meeting records.
should change to `clients and meetings`.

2022-09-30 09:42 UTC, rexong approved these changes
LGTM

2022-09-30 09:42 UTC, sikai00 approved these changes
lgtm

2022-09-30 09:45 UTC, merged